language: objective-c
install:
  - pushd ..
  - git clone https://chromium.googlesource.com/chromium/tools/depot_tools.git
  - export PATH="$PATH":`pwd`/depot_tools
  - popd
  - brew install ninja
script:
  - /trunk/makeall-iossim.sh 
notifications:
  email: false
